name: Prism
main: me.botsko.prism.Prism
version: nightly
softdepend: [WorldEdit,HeroChat]
author: viveleroi
website: http://discover-prism.com
commands:
   prism:
      description: Base command for everything Prism
      usage: /prism ?
      aliases: [pr]
permissions:
    prism.help:
        default: op
    prism.wand.*:
        default: op
        children:
            prism.wand.inspect: true
            prism.wand.profile: true
            prism.wand.rollback: true
            prism.wand.restore: true
    prism.setmy.wand:
        default: op
    prism.lookup:
        default: op
    prism.extinguish:
        default: op
    prism.drain:
        default: op
    prism.preview:
        default: op
    prism.rollback:
        default: op
    prism.restore:
        default: op
    prism.tp:
        default: op
    prism.report:
        default: op
    prism.reload:
        default: op
    prism.delete:
        default: op
    prism.alerts:
        default: op
    prism.bypass-use-alerts:
        default: false
    prism.alerts.ores.ignore:
        default: false
    prism.alerts.use.place.ignore:
        default: false
    prism.alerts.use.break.ignore:
        default: false
    prism.alerts.use.lighter.ignore:
        default: false
    prism.alerts.use.lavabucket.ignore:
        default: false
    prism.alerts.ignore:
        default: false