name: Prism
main: me.botsko.prism.Prism
version: nightly
softdepend: [WorldEdit,HeroChat]
default: op
commands:
   prism:
      description: Base command for everything Prism
      usage: /prism ?
      aliases: [pr]